# In this directory, run the following command to deploy this Cloud Build trigger.
# $ gcloud builds triggers import --source=cloudbuild.trigger.yaml

name: tool-markdown-to-confluence-trigger
description: "Trigger to build markdown-to-confluence tool on change"
timeout: "600"
github:
  owner: dbrtly
  name: learn-cloud-build
  push:
    branch: main
filename: .cloudbuild/builders/markdown-to-confluence/cloudbuild.yaml
includedFiles:
  - ".cloudbuild/builders/markdown-to-confluence/cloudbuild.yaml"
