# In this directory, run the following command to build this builder.
# $ gcloud builds submit

options:
  automapSubstitions: true
  dynamicSubstitutions: true

substitutions:
  _ARTIFACT_REGISTRY_REPO: tools
  _BUILDER_COMMIT_SHA: db78f6a586080bd53fc175559c9d3dcda7bd813d7ad9920884fd344c0fb78b11
  _IMAGE_URI: '${_GOOGLE_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE}:${_BUILDER_COMMIT_SHA}'
  _IMAGE: docs-to-confluence
  _FOLDER_TO_PUBLISH: docs
  _GOOGLE_REGION: us-central1

tags: ['documentation']

steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build --tag 'ghcr.io/markdown-confluence/publish:${_BUILDER_COMMIT_SHA}' \
      --env FOLDER_TO_PUBLISH=${_FOLDER_TO_PUBLISH}

images:
- '${_IMAGE_URI}'
