# In this directory, run the following command to deploy this Cloud Build trigger.
# $ gcloud builds triggers import --source=cloudbuild.trigger.yaml

name: cloud-build-trivy-trigger
description: "Trigger to deploy cloud build triggers on change"
timeout: "600"
github:
  owner: dbrtly
  name: learn-cloud-build
  push:
    branch: main
filename: .cloudbuild/builders/trivy/cloudbuild.yaml
excludedFiles:
  - ".cloudbuild/builders/trivy/README.md"
includedFiles:
  - ".cloudbuild/builders/trivy/*"
