# In this directory, run the following command to deploy this Cloud Build trigger.
# $ gcloud builds triggers import --source=cloudbuild.trigger.yaml

name: cloud-build-test-meta-trigger
description: "Trigger to deploy cloud build triggers on change"
timeout: "600"
github:
  owner: dbrtly
  name: learn-cloud-build
  pull-request:
    branch: main
filename: .cloudbuild/meta-trigger/cloudbuild.yaml
includedFiles:
  - ".cloudbuild/meta-trigger/cloudbuild.trigger.yaml"
  - "docs/.cloudbuild.trigger.yaml"
  - "projects\\/*\\/*cloudbuild.trigger.yaml"
  - "tools\\/*\\/cloudbuild.trigger.yaml"
