# In this directory, run the following command to deploy this Cloud Build trigger.
# $ gcloud builds triggers import --source=cloudbuild.trigger.yaml

name: meta-trigger
description: "Trigger to deploy cloud build triggers on change"
github:
  owner: dbrtly
  name: learn-cloud-build
  push:
    branch: main
filename: .cloudbuild/meta-trigger/cloudbuild.yaml
excludedFiles:
  - "projects/quickstart/*.md"
includedFiles:
  - "projects/quickstart/.cloudbuild.trigger.yaml"
  - "projects/quickstart/.cloudbuild.yaml"
  - "projects/quickstart/*"
